# Generated by Django 3.1.3 on 2024-05-16 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img_src', models.URLField(max_length=1000)),
                ('rover_name', models.CharField(max_length=100)),
                ('camera_name', models.CharField(max_length=100)),
                ('earth_date', models.DateField()),
            ],
        ),
    ]
