# Generated by Django 3.1.3 on 2024-05-16 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_auto_20240515_2149'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Nasa',
            new_name='ImageNasa',
        ),
    ]
