# Generated by Django 5.0.6 on 2024-05-16 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0005_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
